name: Build
on: 
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.1.301
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Clone Dalamud
      run: git clone --recursive https://github.com/goatcorp/Dalamud.git
      working-directory: lib
    - name: Build Dalamud
      run: |
        dotnet restore -r win Dalamud.sln
        MSBuild.exe Dalamud.sln /t:Build /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE /p:WarningLevel=0
      working-directory: lib\Dalamud
    - name: Build
      run: dotnet build --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: XIVComboPlugin\bin\Release\net472\XIVCombo
        if-no-files-found: error
